# Site Settings
title: Swift Dailies
email: apps@ben-boecker.de
description: Daily snippets of useful Swift code.  
#baseurl: "http://localhost:4000"
#url: "http://localhost:4000"
//twitter_username: benboecker
github_username:  SwiftDailies
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
highlighter: rouge